### ISSUE TITLE
inform gentoo about this repo

### ISSUE THREAD

**Issue by mrVanDalo** [gentoo-audio/audio-overlay#10]
proaudio was removed by this commit
https://github.com/gentoo/api-gentoo-org/commit/ffbaecb7f42940dee14097f9825f87a9da02a497

time to fill this gap.

**Comment by simonvanderveldt** [comment]
@mrVanDalo I'd like to add this overlay once we have a couple of ebuilds. Sa 5 or sth like that.
Is that OK?

**Comment by mrVanDalo** [comment]
Sounds good. I bet they want us to take care of the jack package in the upstream

**Comment by simonvanderveldt** [comment]
Yeah, that has some work to do though. Didn't want to get involved with it so far, needs some proper time investment.
I'm still using the one from proaudio because of that :x

**Comment by mrVanDalo** [comment]
The ebuild is the same (or very similar).

**Comment by simonvanderveldt** [comment]
Yeah, but it actually doesn't compile anymore on newer GCCs or LLVM, see https://bugs.gentoo.org/show_bug.cgi?id=617956 and https://bugs.gentoo.org/show_bug.cgi?id=617954

The last one is actually fixed upstream, bit since there hasn't been a JACK2 release in ages it's only on `master` :(
See https://github.com/jackaudio/jack2/issues/220

**Comment by mrVanDalo** [comment]
true, I'm switching to jack1 in some weeks, because it has all the feature I want.

**Comment by magnetophon** [comment]
There is now https://github.com/jackaudio/jack2/releases/tag/v1.9.11-RC1

**Comment by simonvanderveldt** [comment]
@magnetophon I'm already working on getting jack2 versionbumped upstream :)
https://github.com/gentoo/gentoo/pull/4925

**Comment by simonvanderveldt** [comment]
I've created a PR to add the overlay to the list :) https://github.com/gentoo/api-gentoo-org/pull/67

Since you need to have a bugs.gentoo.org account :x and provide an owner I created audio-overlay@googlegroups.com as a mailing list. I'll send an invitation to all of us and make all of us owner of that. We don't have to do anything with the group itself since it just forwards the mails to your own address.

**Comment by simonvanderveldt** [comment]
The above PR has been merged.
We're now listed on https://overlays.gentoo.org/ as well as https://gpo.zugaina.org/Overlays/audio-overlay and available directly through layman.

**Comment by mrVanDalo** [comment]
Sweet! good job @simonvanderveldt
