### ISSUE TITLE
luppp

### ISSUE THREAD

**Issue by norayr** [gentoo-audio/audio-overlay#271]
hello, i'd like to suggest you to add a program luppp.

https://github.com/openAVproductions/openAV-Luppp
http://openavproductions.com/luppp/

most of the dependencies are already there, but there's no ebuild for ntk i guess.

**Comment by norayr** [comment]
i actually managed to compile ntk in prefix, and then i was not able to tell meson, which is a build utility i am not familiar with, to find ntk in the prefix.

**Comment by simonvanderveldt** [comment]
Sorry for the super slow response, we're all pretty busy with other stuff.

It's unfortunate that luppp still uses ntk instead of avtk, but we do have ntk in this repo already so shouldn't really be an issue :)
Did you get any further with the ebuild? I'd expect it to be 99% the same as the [fabla ebuild](https://github.com/gentoo-audio/audio-overlay/blob/master/media-plugins/fabla/fabla-1.9999.ebuild)
