### ISSUE TITLE
media-sound/carla fails with masked by: missing keyword, invalid: DEPEND: Invalid atom (Invalid use dep: '%PYTHON_USEDEP-HAS-BEEN-REMOVED%')

### ISSUE THREAD

**Issue by mazes-80** [gentoo-audio/audio-overlay#311]
PYTHON_USEDEP has been removed

need to change
dev-python/PyQt5[gui,opengl?,svg,widgets,${PYTHON_USEDEP}]
to
$( python_gen_cond_dep 'dev-python/PyQt5[gui,opengl?,svg,widgets,${PYTHON_MULTI_USEDEP}]' )

**Comment by simonvanderveldt** [comment]
Thanks for the report. I don't really understand why we're just seeing this now since the related changes  (https://github.com/gentoo/gentoo/commit/494b83570ff7ee8c5796edc1f9ff578ea962459e#diff-e2e5e221364501ee990fb3dac726ace1) happened some time ago.
But anyway, fix is coming up :)

**Comment by mazes-80** [comment]
furthermore 17.1 profile lv2 plugins to be installed at the right place

sed -i -e "/^LIBDIR/s/lib$/$(get_libdir)/" Makefile || die
should be added to src_prepare
compilation and linking are fine, but the plugin is not installed system-wide, so mostly unusable

this is a kind of generic suggestion that may apply to virtually any package installing lv2 plugins

**Comment by simonvanderveldt** [comment]
@mazes-80 I've created #330 for tracking the changes required for the 17.1 profile, it's not related to this issue.
I haven't switched and don't plan to switch until it becomes the default because the proposed changes don't make sense to me. Once it's become the default I effectively no longer have a choice so will have to migrate then. Anyway, that means I currently don't have a way to test this. If it's fixable without breaking 17.0 compatibility then I guess we could already introduce the necessary changes.
