### ISSUE TITLE
Pic a jekyll theme for https://gentoo-audio.github.io/

### ISSUE THREAD

**Issue by mrVanDalo** [gentoo-audio/audio-overlay#49]
Here are some themes for jekyll : http://jekyllthemes.org/

Just post your preferred theme here and we will vote.

**Comment by simonvanderveldt** [comment]
I'm quiet OK with the way it looks now. Only thing I'd like to change is to have the navigation at the top/horizontal (or maybe to the left) and get rid of the strangely located "gentoo audio overlay" text on the right side, like
![image](https://user-images.githubusercontent.com/204286/27514946-da491bea-5998-11e7-8845-5f994fd336cc.png)
(this would still need navigation above it)

P.S. OK if we create an issue in the site's repo for this instead of in the overlay's repo?

**Comment by mrVanDalo** [comment]
Yeah I agree. I don't have an eye for beauty and all that (I'm not a designer) (look at my page : http://ingolf-wagner.de/ )

But I agree I want the navigation in the top as well. 

I'm Ok with everything about the issues. I use bugwarrior and it will pull from both repositories.

**Comment by mrVanDalo** [comment]
Closed because of inactivity
