### ISSUE TITLE
How to handle wineasio's need for asio.h from the ASIO SDK

### ISSUE THREAD

**Issue by simonvanderveldt** [gentoo-audio/audio-overlay#92]
Wanted to discuss this before I create a PR.
I want to add `app-emulation/wineasio`, which was requested in #9

wineasio needs the `asio.h` header which is part of the the ASIO SDK. This SDK is covered by the "Steinberg ASIO SDK Licensing Agreement" (see http://www.steinberg.net/sdk_downloads/asiosdk2.3.zip, it's a PDF in there).
The proaudio overlay addressed this by adding a `media-libs/asiosdk` package which has a `fetch` restriction, i.e. the user needs to manually download the file and only then it can be installed, which is obviously a sub-optimal user experience.

I'm considering the option to simply include the `asio.h` file in the `./files` directory of the wineasio package.
In the Steinberg ASIO SDK Licensing Agreement there seems to be just one paragraph really relevant for this (emphasis mine):
> The Licensee has no permission to sell, license, give-away and/or distribute the
Licensed Software Developer Kit **or parts of it for the use as software developer kit** in
any way, for example, integrated in any framework application, on any medium,
including the Internet, to any other person, including sub-licensors of the Licensee or
companies where the Licensee has any involvement. This includes re-working this
specification, or reverse-engineering any products based upon this specification.

We're talking about "parts of it", since it's just one header.
And since we're not making this "part of it" available as part of a software development kit, but just as a means to build the already developed application, I see no objections in this license for us to add the `asio.h` file to the wineasio package.

What do you think?

**Comment by domichel** [comment]
It is "integrated in any framework application"., which apply if I understand it right, precisely to any application. This imply we cannot legally do it. Now I am not a layer, but I think I am right. I also think than otherwise, all distributions would provide asio.h instead of depending on a fetch restricted software.

If I look to arch linux, they have no fetch restriction in their steinberg-asio package in aur. It just download the archive with
`wget http://www.steinberg.net/sdk_downloads/asiosdk2.3.zip`
and the only install the license file, and the asio.h file in /usr/include/steinberg-asio.

I think this is the best way to go, remove the fetch instruction, provide the license and install the asio.h file.

Annexes:
https://aur.archlinux.org/packages/steinberg-asio/
https://aur.archlinux.org/packages/wineasio/

**Comment by simonvanderveldt** [comment]
> It is "integrated in any framework application"., which apply if I understand it right, precisely to any application

A "framework application" is like an example that other can use to start from, another word for it would be a skeleton. It's meant as a more specific definition of a "software deloper kit".

This is a case that doesn't apply to us.

**Comment by domichel** [comment]
> 
> This is a case that doesn't apply to us.
> 

OK. I am not a layer, which imply it is difficult to me to be sure of
anything. If you are sure, we can do it.

But in case of doubt, I see nothing which stop us to remove the fetch
restriction. If Steinberg doesn't want to allow users to make direct
downloads, it is up to them to change their website. And other
distribution are doing this.

So, the question is to know if it is any doubt. For me it is because I
am not a layer.

Dominique

**Comment by simonvanderveldt** [comment]
> think this is the best way to go, remove the fetch instruction, provide the license and install the asio.h file.

OK, I'll do that
